### ISSUE TITLE
Build fails on macOS

### ISSUE THREAD

**Issue by lbuczkow** [mlewe/BlossomV.jl#11]
Build fails on macOS with a message "LoadError: Provider BinDeps.BuildProcess failed to satisfy dependency blossom5int32". This is due to the fact BinDeps tries to open .dylib rather than .so file. It can be fixed by creating links in build.jl:

                    `cp -f blossom5.so $prefix/lib/blossom5int32.so`
                    `ln -s $prefix/lib/blossom5int32.so $prefix/lib/blossom5int32.dylib`
(...)
                    `cp -f blossom5.so $prefix/lib/blossom5float64.so`
                    `ln -s $prefix/lib/blossom5float64.so $prefix/lib/blossom5float64.dylib`

**Comment by mlewe** [comment]
The right way to go about this would probably be to link the library with `-dynamiclib` instead of `-shared` on Mac OS X.
I don't have a machine to test this on, but I would gladly accept patches to support this package on operating systems other than Linux.

**Comment by mlewe** [comment]
Solved in v0.4.2
