### ISSUE TITLE
Getting solution total cost

### ISSUE THREAD

**Issue by Bebotron** [mlewe/BlossomV.jl#19]
Not sure if an issue is the right place, since this is more of a question/suggestion. But I was trying to figure out the final cost of the solution. Currently, we can get the edge matches for the solution, and it's pretty straightforward to simply write a script that will calculate the total cost after calling `get_all_matches`, but I figured this information should be available in the structure `PerfectMatchingCtx.ptr` and should be able to be retrieved with a ccall, I just have no idea how to do that.

Is there a way to see the contents of what the object `PerfectMatchingCtx.ptr` is pointing to contains?

**Comment by mlewe** [comment]
The total cost of the matching is not not already calculated and available.
There exists code inside of the BlossomV C++ library for calculating the total cost (see `misc.cpp`), but I don't see any benefit compared to iterating over the result of `get_all_matches`.

**Comment by Bebotron** [comment]
Ok yea, iterating over the solution is easier. Thanks!
