### ISSUE TITLE
suppressing prints

### ISSUE THREAD

**Issue by CarloLucibello** [mlewe/BlossomV.jl#8]
Hi @mlewe ,
I'm improperly opening an issue here, because unfortunately the wrapped c++ code is not on github.
I'd like to suppress this printings 
```
perfect matching with 4 nodes and 4 edges
    starting init...done [0.000 secs]. 0 trees
    .
done [0.000 secs]. 0 grows, 0 expands, 0 shrinks
    expands: [0.000 secs], shrinks: [0.000 secs], dual updates: [0.000 secs]
```
since I have to run the algorithms on many samples.
I know they don't come from here,  but maybe you know of some verbosity flag that can be passed through ccall to the matching function.

Bye,
Carlo

**Comment by mlewe** [comment]
Hi @CarloLucibello, I tried to fix the problem in the commit linked above.
Is this good enough for you? In that case I can tag a new release and get it published.

**Comment by CarloLucibello** [comment]
that was fast, thanks!

I get this, even after a Pkg.build("BlossomV")
```
ERROR: LoadError: LoadError: ccall: could not find function matching_verbose in library /home/carlo/.julia/v0.5/BlossomV/deps/usr/lib/blossom5.so
 in Type at /home/carlo/.julia/v0.5/BlossomV/src/BlossomV.jl:19 [inlined]
 in Matching(::Int32, ::Int32) at /home/carlo/.julia/v0.5/BlossomV/src/BlossomV.jl:42
...
```

**Comment by mlewe** [comment]
I fixed the type error in e8cb4f7, thanks for pointing that out.

The error stems from the shared library not being rebuilt. Try deleting `deps/usr`, `deps/src` and `deps/deps.jl` and running `Pkg.build("BlossomV")` again. I'm not sure how to avoid that, sorry.

**Comment by CarloLucibello** [comment]
deleting deps/usr, deps/src  and running Pkg.build("BlossomV") does the job. Maybe changing deps/build.jl
like this
```julia
provides(BuildProcess,
    (@build_steps begin
        `rm -r src/*`
        `rm -r usr/*`
        GetSources(blossom5)
       .....
```
could solve the update problem?

**Comment by mlewe** [comment]
It wouldn't solve the update problem, because the build doesn't get kicked off, when blossom5.so already exists. Some check if the existing binary is up to date would be necessary.

**Comment by CarloLucibello** [comment]
well let's tag a new version now that LGExtras with BlossomV dependence has not been tagged for 0.5 yet

**Comment by mlewe** [comment]
I fixed the problem by adding a version check. `Pkg.build` now triggers a rebuild as intended, when the binary is out of date.
I tagged a new version (v0.2.0), see JuliaLang/METADATA.jl#6692.
